SocialGouv/kontinuous

- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-runs-map.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-command.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-sql.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-uses-relative.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-uses-self-ref.dev.yaml
- plugins/fabrique/jobs/create-db/create-secret.sh
- plugins/fabrique/jobs/create-db/use.yaml
may be useful when using ports different than 5432
> fix(create-db): use PGPORT

- packages/kontinuous/tests/__snapshots__/ingress-annotations.prod.yaml
- packages/kontinuous/tests/__snapshots__/metabase.prod.yaml
- packages/kontinuous/tests/__snapshots__/oauth2-proxy-metabase.prod.yaml
- plugins/fabrique/charts/metabase/templates/deployment.yaml
> fix(metabase): reduce startupDelay

- packages/kontinuous/src/build/builder.js
show error message when helm fails
> fix(builder): show helm exceptions

- packages/kontinuous/tests/__snapshots__/app-simple-tag.dev.yaml
- packages/kontinuous/tests/__snapshots__/app-simple-tag.prod.yaml
- packages/kontinuous/tests/__snapshots__/app-simple.dev.yaml
- packages/kontinuous/tests/__snapshots__/app-simple.prod.yaml
- packages/kontinuous/tests/__snapshots__/ingress-annotations.prod.yaml
- packages/kontinuous/tests/__snapshots__/init-container.dev.yaml
- packages/kontinuous/tests/__snapshots__/inline-values.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-command.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-sql.dev.yaml
- packages/kontinuous/tests/__snapshots__/long-branch-host-patch.dev.yaml
- packages/kontinuous/tests/__snapshots__/long-branch-host.dev.yaml
- packages/kontinuous/tests/__snapshots__/metabase.prod.yaml
- packages/kontinuous/tests/__snapshots__/oauth2-proxy-metabase.prod.yaml
- packages/kontinuous/tests/__snapshots__/oauth2-proxy.prod.yaml
- packages/kontinuous/tests/__snapshots__/post-renderer.dev.yaml
- packages/kontinuous/tests/__snapshots__/redirect.prod.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.dev.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.preprod.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.prod.yaml
- packages/kontinuous/tests/__snapshots__/values-js.dev.yaml
- packages/kontinuous/tests/__snapshots__/volume-add.dev.yaml
- plugins/contrib/deploy-with/kapp.js
kapp: add waitCheckInterval and waitConcurrency options
> fix(kapp) add waitCheckInterval and waitConcurrency options

- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-runs-map.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-command.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-sql.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-uses-relative.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-uses-self-ref.dev.yaml
- plugins/contrib/jobs/build/use.yaml
Add ability to skip build when docker image with same sha has already been registered
> feat(build): add with.skipExisting

- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/samples/jobs-build-options/config.yaml
- packages/kontinuous/tests/samples/jobs-build-options/env/dev/values.yaml
- plugins/contrib/jobs/build/use.yaml
add ability to pass additionnal build arguments ex : `--insecure --single-snapshot --ignore-path=/product_uuid --compressed-caching=false` for kaniko
> feat(build): add build.buildOptions

- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- plugins/contrib/jobs/build/use.yaml
> fix(job-build): fix skipExisting docker image

- packages/kontinuous/tests/__snapshots__/app-simple-tag.dev.yaml
- packages/kontinuous/tests/__snapshots__/app-simple-tag.prod.yaml
- packages/kontinuous/tests/__snapshots__/app-simple.dev.yaml
- packages/kontinuous/tests/__snapshots__/app-simple.prod.yaml
- packages/kontinuous/tests/__snapshots__/init-container.dev.yaml
- packages/kontinuous/tests/__snapshots__/inline-values.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-command.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-sql.dev.yaml
- packages/kontinuous/tests/__snapshots__/long-branch-host-patch.dev.yaml
- packages/kontinuous/tests/__snapshots__/long-branch-host.dev.yaml
- packages/kontinuous/tests/__snapshots__/post-renderer.dev.yaml
- packages/kontinuous/tests/__snapshots__/redirect.prod.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.dev.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.preprod.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.prod.yaml
- packages/kontinuous/tests/__snapshots__/values-js.dev.yaml
- packages/kontinuous/tests/__snapshots__/volume-add.dev.yaml
- plugins/contrib/charts/contrib-helpers/templates/_anti-affinity.yaml
This reverts commit 4622d8aefd27ebc582195ed51a6319d8cf1e191c.
> Revert "fix(podAntiAffinity): use preferred affinity (#54)"

- packages/kontinuous/src/cli/options.js
- packages/kontinuous/src/test/index.js
- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- plugins/contrib/deploy-with/kapp.js
- plugins/contrib/jobs/build/use.yaml
Add ability to define a `local` environment
> feat: local environment

- packages/kontinuous/tests/__snapshots__/app-simple-tag.dev.yaml
- packages/kontinuous/tests/__snapshots__/app-simple-tag.prod.yaml
- packages/kontinuous/tests/__snapshots__/app-simple.dev.yaml
- packages/kontinuous/tests/__snapshots__/app-simple.prod.yaml
- packages/kontinuous/tests/__snapshots__/init-container.dev.yaml
- packages/kontinuous/tests/__snapshots__/inline-values.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-command.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-sql.dev.yaml
- packages/kontinuous/tests/__snapshots__/long-branch-host-patch.dev.yaml
- packages/kontinuous/tests/__snapshots__/long-branch-host.dev.yaml
- packages/kontinuous/tests/__snapshots__/post-renderer.dev.yaml
- packages/kontinuous/tests/__snapshots__/redirect.prod.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.dev.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.preprod.yaml
- packages/kontinuous/tests/__snapshots__/sample-1.prod.yaml
- packages/kontinuous/tests/__snapshots__/values-js.dev.yaml
- packages/kontinuous/tests/__snapshots__/volume-add.dev.yaml
- plugins/contrib/charts/contrib-helpers/templates/_anti-affinity.yaml
use preferred vs required strategy as default
> fix: use preferredDuringSchedulingIgnoredDuringExecution

- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- plugins/contrib/jobs/build/use.yaml
> fix: build.skipExisting with harbor

- packages/kontinuous/tests/__snapshots__/deactivate.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-runs-map.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-command.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-seed-sql.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-uses-relative.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-uses-self-ref.dev.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.dev.yaml
- plugins/contrib/jobs/create-db/use.yaml
- plugins/contrib/jobs/deactivate/use.yaml
- plugins/contrib/jobs/seed-db/use.yaml
Set `backOffLimit` to 3 for jobs :
- create-db
- drop-db
- seed-db
- deactivate
> fix: retry jobs too

- docs/README.md
- docs/advanced/deploy.md
- docs/advanced/webhook.md
proposition:
- move deploy section after intro, i think it comes after ?
- fixup deploy/webhook pages
- remove some legacy ? doc
> docs: deployment

- docs/README.md
Ce serait p-e pas mal de mettre un exemple explicite de values.yaml pour capter l'essence ? je sais pas si celui ci est le meilleur
> docs: wording

- .github/jsonschema/jsonschema-invalid.yml
- .github/jsonschema/jsonschema-valid.yml
- .github/workflows/tests-jsonschema.yml
- docs/values.schema.json
- plugins/contrib/charts/app/kontinuous.values.schema.json
- plugins/contrib/charts/jobs/kontinuous.values.schema.json
- plugins/contrib/jobs/build-kaniko/use.schema.json
- plugins/contrib/jobs/create-db/use.schema.json
- plugins/contrib/jobs/deactivate/use.schema.json
- plugins/contrib/jobs/drop-db/use.schema.json
- plugins/contrib/jobs/pg-restore/use.schema.json
- plugins/contrib/jobs/psql/use.schema.json
- plugins/contrib/jobs/seed-db/use.schema.json
Make optional properties not available in known charts and jobs
Add non-reg test for json-schemas
> tests: json-schema

- packages/webhook/src/cron/clean-artifact.js
> fix: up rimraf version usage

- packages/kontinuous/tests/__snapshots__/job-builds.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.dev.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.preprod.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.prod.yaml
- plugins/contrib/charts/contrib-helpers/templates/_job.yaml
- plugins/contrib/jobs/build/use.yaml
> fix: deprecated seccomp kube1-25

- packages/kontinuous/tests/__snapshots__/app-probes.dev.yaml
- packages/kontinuous/tests/samples/app-probes/config.yaml
- packages/kontinuous/tests/samples/app-probes/values.yaml
- plugins/contrib/charts/contrib-helpers/templates/_probes.yaml
Fix helm merge that prevented from overriding some values like :
```yaml
app:
enabled: true
startupProbe:
initialDelaySeconds: 123
failureThreshold: 124
periodSeconds: 125
```
> fix(probes): fix helm merge

- packages/kontinuous/tests/__snapshots__/ingress-annotations.prod.yaml
- packages/kontinuous/tests/__snapshots__/metabase.prod.yaml
- packages/kontinuous/tests/__snapshots__/oauth2-proxy-metabase.prod.yaml
- packages/kontinuous/tests/__snapshots__/oauth2-proxy.prod.yaml
- plugins/contrib/charts/metabase/templates/deployment.yaml
- plugins/contrib/charts/oauth2-proxy/templates/deployment.yaml
Add renovate annotations for metabase and oauth2-proxy
> chore: add some renovate annotations

- .github/workflows/tests-jsonschema.yml
- plugins/contrib/charts/app/kontinuous.values.schema.json
- plugins/contrib/charts/jobs/kontinuous.values.schema.json
> fix(jsonschema): fix app.probes and jobs.use

- packages/kontinuous/tests/__snapshots__/job-builds.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.dev.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.preprod.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.prod.yaml
- plugins/contrib/jobs/build/use.yaml
fixing https://github.com/SocialGouv/support/issues/380
> fix: add latest tag to build

- packages/common/config/load-config.js
- plugins/contrib/patches/rancher-project-id.js
> fix: isLocal and optional rancher project id

- .github/workflows/tests-kubeconform.yml
Ensure kube API snapshots validity with [kubeconform](https://github.com/yannh/kubeconform)
exclude CNPG+sealed-secrets validation
> tests: add kubeconform on snapshots

- plugins/contrib/charts/jobs/kontinuous.values.schema.json
- plugins/contrib/jobs/create-db/use.schema.json
- plugins/contrib/jobs/seed-db/use.schema.json
> fix(jsonschema): minor fixes

- packages/kontinuous/tests/__snapshots__/redis-volume.prod.yaml
- packages/kontinuous/tests/__snapshots__/redis.prod.yaml
- packages/kontinuous/tests/samples/redis-volume/config.yaml
- packages/kontinuous/tests/samples/redis-volume/env/prod/values.yaml
- packages/kontinuous/tests/samples/redis/config.yaml
- packages/kontinuous/tests/samples/redis/env/prod/values.yaml
- plugins/contrib/charts/redis/templates/deployment.yaml
- plugins/contrib/charts/redis/values.yaml
Add volumes options for redis chart. copied from app chart
> fix(redis): add values volumes options

- packages/wait-needs/Dockerfile
test de reduction de l'image finale;
j'ai pas compris cette ligne : 
`RUN groupadd -g 1001 ubuntu && useradd -rm -d /home/ubuntu -s /bin/bash -g ubuntu -G sudo -u 1001 ubuntu`
on peut utiliser l'user node déjà dans l'image ?
> chore: use alpine for wait-needs docker image

- plugins/contrib/debug-manifests/01-resources-tree-infos.js
- plugins/contrib/debug-manifests/tests/__snapshots__/resources-tree-infos.test.js.snap
- plugins/contrib/debug-manifests/tests/samples/template.yaml
improve debug tree readability (see snapshots)
> fix(debug): better manifest tree

- plugins/contrib/jobs/cnpg-create-secrets/create-secrets.sh
- plugins/contrib/jobs/cnpg-create-secrets/use.yaml
- plugins/fabrique/charts/pg/values.yaml
- fix dbSecretName
- dont include port in pgHost
> fix(pg): fix dbSecretName

- packages/kontinuous/tests/__snapshots__/extends-ovh.dev.yaml
- plugins/fabrique/extends/ovh.yaml
Its not yet possible to modify this value with OVH
> fix(ovh): custom maxPods

- packages/kontinuous/tests/__snapshots__/job-builds.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-options.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build-stage.dev.yaml
- packages/kontinuous/tests/__snapshots__/jobs-build.dev.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.dev.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.preprod.yaml
- packages/kontinuous/tests/__snapshots__/repo.domifa.prod.yaml
- packages/kontinuous/tests/__snapshots__/socialgouv-autodevops-override.dev.yaml
- packages/kontinuous/tests/__snapshots__/socialgouv-autodevops.dev.yaml
- plugins/contrib/jobs/build/use.yaml
- plugins/fabrique/kontinuous.yaml
related to https://github.com/SocialGouv/helm-charts/pull/8
> feat: buildkit-service optional feature

- packages/kontinuous/tests/__snapshots__/extends-ovh.dev.yaml
- packages/kontinuous/tests/__snapshots__/extends-ovh.prod.yaml
- packages/kontinuous/tests/samples/extends-ovh/values.yaml
Add app with ingress in ovh-extends test
> tests: add more ovh tests

- packages/kontinuous/tests/__snapshots__/ingress-annotations.prod.yaml
- packages/kontinuous/tests/__snapshots__/ingress-betagouv.prod.yaml
- packages/kontinuous/tests/__snapshots__/ingress-custom-annotations.prod.yaml
- packages/kontinuous/tests/__snapshots__/ingress-custom-certs.prod.yaml
- packages/kontinuous/tests/__snapshots__/metabase.prod.yaml
- packages/kontinuous/tests/__snapshots__/oauth2-proxy-metabase.prod.yaml
- plugins/contrib/charts/metabase/templates/deployment.yaml
https://www.metabase.com/blog/security-advisory
> fix: upgrade metabase to v0.46.6.1

- docs/faq.md
> docs: add faq

- .github/actions/build-images/action.yaml
Reverts SocialGouv/kontinuous#381
> fix: major image revert

- packages/kontinuous/tests/__snapshots__/extends-ovh.dev.yaml
- packages/kontinuous/tests/__snapshots__/extends-ovh.prod.yaml
- packages/kontinuous/tests/__snapshots__/override-env-default.dev.yaml
- packages/kontinuous/tests/__snapshots__/pg.prod.yaml
- packages/kontinuous/tests/samples/extends-ovh/config.yaml
- packages/kontinuous/tests/samples/override-env-default/config.yaml
- packages/kontinuous/tests/samples/pg/config.yaml
- plugins/fabrique/charts/pg/values.yaml
- use superuser secret for backups
- restore previous destinationPath (fixed in the helm-charts)
> fix(cnpg): use superuser secret for backups

- docs/values.schema.json
- plugins/contrib/charts/app/kontinuous.values.schema.json
- plugins/fabrique/charts/pg/kontinuous.values.schema.json
Ajout du JSON schema pour le chart pg
> chore(jsonschema): add pg chart schema

- docs/faq.md
> docs: add --chart documentation

- .vscode/settings.json
- plugins/contrib/charts/contrib-helpers/templates/_job.yaml
needed for the work in progress to improve buildkit resilience to service downtime and performances
> fix: jobs add security context options
